### ISSUE TITLE
[Config] Old Synth Configs Not Transferred

### ISSUE THREAD

**Issue by Mechoid** [Baystation12/custom-items#15]
The previous custom_synth config's entries didn't seem to be transferred, leaving some borgs (And a few AI's) without their sprites. I've put a ? by the ones I'm not certain the name of, or don't know the name.
Borg:
-Mechoid: Acheron 7*
-Morguemeat: Shudder (?)
-Pandarsenic: Phoenix 121 (?)
-Donofnyc3: N.O.S.E.
-Pear120: Angel (?)
-Atlantiscze: Angel (?)
-Renscorch: (?)
-Searif: Frosty (?)
Papadrow, Nakiavalkov, and Fonedsky aren't here because I don't think I ever actually saw their borgs in the time when they were merged before the custom-items branch was made.

**Comment by GinjaNinja32** [comment]
Atlantis is Angel/AngelOS, no idea of the others.

**Comment by mwerezak** [comment]
You could probably go looking through the old custom cyborg requests.

**Comment by Zuhayr** [comment]
Would prefer to just have people ask to get readded.

**Comment by Raptor1628** [comment]
http://baystation12.net/forums/threads/custom-borg-sprite-list-update.579/

**Comment by Raptor1628** [comment]
Alright, everyone that has asked has had theirs readded. Searif, Nakia, and Foned haven't asked and aren't on the config yet.

**Comment by Zuhayr** [comment]
Going to go ahead and close this then.
