### ISSUE TITLE
Mugs do not inherit from host file

### ISSUE THREAD

**Issue by SovietCyanide** [Baystation12/custom-items#207]
When filling a mug with tea or any other item, the sprite becomes invalid. I believe that the inner 'drink' does not copy over. Also a problem with the in-hand sprite.

**Comment by PsiOmegaDelta** [comment]
Dev note: Sounds like mugs need to use the base icon extension similar to, for example, zippos

**Comment by babydoll** [comment]
This particular issue has been solved. Also note that no custom-items currently have in hand icons.
