### ISSUE TITLE
borg sprite limit reached

### ISSUE THREAD

**Issue by Casper3667** [Baystation12/custom-items#72]
yep, the sprite limit is reached and i'm unable to get the stuff working to add in more sprites for another guy.

**Comment by Kasuobes** [comment]
Perhaps a custom item cleanup is in order to remove unused sprites from inactive players.

**Comment by PsiOmegaDelta** [comment]
Perhaps, but with borg icons being so numerous it'll only be a matter of time until it's full again.
Better to make a system that enables having multiple icon files.
